# scripts/make_meta_summary_table.R
#
# Builds a compact meta-summary table aggregating the 18 completed team tests
# by theory sub-family, and writes tables/meta_summary.tex (a self-contained
# booktabs tabular) for inclusion in draft_APSG.tex.
#
# One row per sub-family + a Total row, with columns:
#   Sub-family | Registered (k) | Completed | beta>0 | beta<0 |
#   Nominal p<.05 | Bonferroni p<.05
#
# The Bonferroni denominator k is the PRE-REGISTERED family size (7/6/5/4),
# fixed in advance and identical to the dotted thresholds in
# scripts/make_main_coef_figure.R. We deliberately do NOT use the count of
# completed teams as k: the correction is set by the number of pre-registered
# tests, not by how many have finished.
#
# Run from project root:  Rscript scripts/make_meta_summary_table.R

suppressPackageStartupMessages({
  library(tidyverse)
  library(jsonlite)
})

ROOT <- "C:/Users/torewig/Dropbox (Privat)/!!!!FORSKNING!!!!!/AUTOKNOW_ERC_COG/Papers/P02_autocracy-science-agent-orchestra"
if (!dir.exists(file.path(ROOT, "teams"))) {
  # Fall back to the working directory when the absolute path is unavailable.
  ROOT <- getwd()
}
setwd(ROOT)

# The same 18 teams as the main-coefficients figure. EXCLUDES team_23, which
# has a primary_results.json but belongs to the queued ideological-alignment
# sub-family; including it would contradict the "18 of 25" narrative.
teams_done <- sprintf("%02d", c(1:4, 7:9, 11, 13:22))

# Sub-family metadata: canonical display order, label, and pre-registered size
# k (the fixed Bonferroni denominator). Copied from make_main_coef_figure.R.
fam_meta <- tribble(
  ~family,                     ~label,                       ~k,
  "topic-avoidance",           "Topic avoidance",            7L,
  "framing-neutrality",        "Framing neutrality",         6L,
  "collaboration-constraint",  "Collaboration constraint",   5L,
  "visibility-suppression",    "Visibility suppression",     4L
) |>
  mutate(label = fct_inorder(label))

read_team <- function(tid) {
  f <- file.path(ROOT, sprintf("teams/team_%s/analysis/primary_results.json", tid))
  j <- fromJSON(f)
  tibble(
    team   = tid,
    family = j$theory_family,
    beta   = as.numeric(j$coefficient),
    p      = as.numeric(j$p_value)
  )
}

d <- map_dfr(teams_done, read_team)

# Guard: every completed team must map to one of the four families above.
unknown <- setdiff(unique(d$family), fam_meta$family)
if (length(unknown) > 0) {
  stop("Unrecognised theory_family value(s): ", paste(unknown, collapse = ", "),
       "\nUpdate fam_meta in make_meta_summary_table.R.")
}

# Apply the fixed-k Bonferroni rule (p_adj = p * k, capped at 1), then count.
agg <- d |>
  left_join(fam_meta, by = "family") |>
  mutate(p_adj = pmin(p * k, 1)) |>
  group_by(label, k) |>
  summarise(
    completed   = n(),
    n_pos       = sum(beta > 0),
    n_neg       = sum(beta < 0),
    n_sig_raw   = sum(p < 0.05),
    n_sig_bonf  = sum(p_adj < 0.05),
    .groups = "drop"
  ) |>
  arrange(label)

total <- agg |>
  summarise(
    label      = "Total",
    k          = sum(k),
    completed  = sum(completed),
    n_pos      = sum(n_pos),
    n_neg      = sum(n_neg),
    n_sig_raw  = sum(n_sig_raw),
    n_sig_bonf = sum(n_sig_bonf)
  )

# Console summary for verification.
cat("\n=== Meta-summary by sub-family ===\n")
print(as.data.frame(agg))
cat("\n--- Totals ---\n")
print(as.data.frame(total))

# -----------------------------------------------------------------------------
# Emit a self-contained booktabs tabular to tables/meta_summary.tex
# -----------------------------------------------------------------------------
fmt_row <- function(label, k, completed, n_pos, n_neg, n_sig_raw, n_sig_bonf) {
  sprintf("%s & %d & %d & %d & %d & %d & %d \\\\",
          label, k, completed, n_pos, n_neg, n_sig_raw, n_sig_bonf)
}

body_rows <- pmap_chr(
  list(as.character(agg$label), agg$k, agg$completed,
       agg$n_pos, agg$n_neg, agg$n_sig_raw, agg$n_sig_bonf),
  fmt_row
)

total_row <- with(total,
  sprintf("\\textbf{%s} & \\textbf{%d} & \\textbf{%d} & \\textbf{%d} & \\textbf{%d} & \\textbf{%d} & \\textbf{%d} \\\\",
          label, k, completed, n_pos, n_neg, n_sig_raw, n_sig_bonf))

lines <- c(
  "% Auto-generated by scripts/make_meta_summary_table.R - do not edit by hand.",
  "\\begin{tabular}{@{}l c c c c c c@{}}",
  "\\toprule",
  " & Registered & Completed & \\multicolumn{2}{c}{Sign of $\\hat{\\beta}$} & Nominal & Bonferroni \\\\",
  "\\cmidrule(lr){4-5}",
  "Sub-family & ($k$) & tests & $>0$ & $<0$ & $p<.05$ & $p<.05$ \\\\",
  "\\midrule",
  body_rows,
  "\\midrule",
  total_row,
  "\\bottomrule",
  "\\end{tabular}"
)

out_path <- file.path(ROOT, "tables/meta_summary.tex")
writeLines(lines, out_path)
cat(sprintf("\nWrote: %s\n", out_path))
